import = ["~/Downloads/alacritty-master/dracula.toml"]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]

[font]
normal = { family = "Fira Code", style = "Retina" }
size = 14

[window]
option_as_alt = "Both"
startup_mode = "Fullscreen"
